/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import java.io.IOException;
import javax.swing.JOptionPane;
import respaldo.Respaldo;
import javax.swing.JScrollPane;
import restauracion.Restauracion;

/**
 *
 * @author Ruben
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        // Crear un JScrollPane y agregar jDesktopPane1 dentro de él
        JScrollPane scrollPane = new JScrollPane(jDesktopPane1);

        // Configurar el tamaño de jDesktopPane1 para que sea más grande que la ventana principal
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        // Reemplazar el layout original con el JScrollPane
        setContentPane(scrollPane);

        // Volver a empacar para ajustar el JScrollPane
        pack();
        setLocationRelativeTo(null);

        Respaldo instanciaRespaldo = Respaldo.getInstance();
        Restauracion instanciaRestauracion = Restauracion.getInstance();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        DpFormulario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVender = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuProducto = new javax.swing.JMenuItem();
        jMenuProveedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Backup = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(966, 1260));
        jPanel1.setNextFocusableComponent(jMenuBar1);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DpFormulario.setFont(new java.awt.Font("Sitka Text", 3, 10)); // NOI18N
        DpFormulario.setForeground(new java.awt.Color(153, 153, 255));
        DpFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DpFormulario.setText("Programa de Venta:   Ingenieros: Musicalizacion: Gabriel Ponce /Experto en algo: Jonathan Galarza/ El de la idea y nada mas:  Ruben Villegas"); // NOI18N
        DpFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DpFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        DpFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DpFormulario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jDesktopPane1.setLayer(DpFormulario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        DpFormulario.getAccessibleContext().setAccessibleName("Programa de Venta\nIngenieros:\nMusicalizacion: Gabriel Ponce \nExperto en algo: Jonathan Galarza\nEl de la idea y nada mas:  Ruben Villegas");
        DpFormulario.getAccessibleContext().setAccessibleDescription("");

        jMenuVender.setText("Vender");
        jMenuVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVenderMouseClicked(evt);
            }
        });
        jMenuVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVenderActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Venta");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuVender.add(jMenuItem5);

        jMenuItem1.setText("Presupesto");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuVender.add(jMenuItem1);

        jMenuBar1.add(jMenuVender);

        jMenu2.setText("Administracion");

        jMenuCliente.setText("Clientes");
        jMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClienteMouseClicked(evt);
            }
        });
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCliente);

        jMenuProducto.setText("Productos");
        jMenuProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProductoMouseClicked(evt);
            }
        });
        jMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuProducto);

        jMenuProveedor.setText("Proveedores");
        jMenuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuProveedor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informes");

        jMenuItem3.setText("Buscar por Comprobante");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Buscar por Fecha");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem2.setText("Buscar Proveedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Backup");

        Backup.setText("Crear Backup");
        Backup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackupMouseClicked(evt);
            }
        });
        Backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackupActionPerformed(evt);
            }
        });
        jMenu1.add(Backup);

        jMenuItem7.setText("Recuperar Backup");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem7MouseClicked(evt);
            }
        });
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Salir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVenderActionPerformed

    }//GEN-LAST:event_jMenuVenderActionPerformed

    private void jMenuVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVenderMouseClicked

    }//GEN-LAST:event_jMenuVenderMouseClicked

    private void jMenuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClienteMouseClicked
        Formulario.ForClientes objetoFormularioCliente = new Formulario.ForClientes();
        DpFormulario.add(objetoFormularioCliente);
        objetoFormularioCliente.setVisible(true);
    }//GEN-LAST:event_jMenuClienteMouseClicked

    private void jMenuProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProductoMouseClicked
        Formulario.ForProducto objetoFormularioProducto = new Formulario.ForProducto();
        DpFormulario.add(objetoFormularioProducto);
        objetoFormularioProducto.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuProductoMouseClicked

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        Formulario.ForClientes objetoFormularioCliente = new Formulario.ForClientes();
        DpFormulario.add(objetoFormularioCliente);
        objetoFormularioCliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProductoActionPerformed
        Formulario.ForProducto objetoFormularioProducto = new Formulario.ForProducto();
        DpFormulario.add(objetoFormularioProducto);
        objetoFormularioProducto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuProductoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Formulario.ForBuscarComprobante objetoFormularioBuscarComprobante = new Formulario.ForBuscarComprobante();
        DpFormulario.add(objetoFormularioBuscarComprobante);
        objetoFormularioBuscarComprobante.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Formulario.ForBuscarPorFecha objetoFormularioBuscarPoFecha = new Formulario.ForBuscarPorFecha();
        DpFormulario.add(objetoFormularioBuscarPoFecha);
        objetoFormularioBuscarPoFecha.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        System.exit(0);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Formulario.ForVentas objetoFormularioVenta = new Formulario.ForVentas();
        DpFormulario.add(objetoFormularioVenta);
        objetoFormularioVenta.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
        Formulario.ForVentas objetoFormularioVenta = new Formulario.ForVentas();
        DpFormulario.add(objetoFormularioVenta);
        objetoFormularioVenta.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void jMenuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProveedorActionPerformed
        Formulario.ForProveedores objetoFormularioProveedor = new Formulario.ForProveedores();
        DpFormulario.add(objetoFormularioProveedor);
        objetoFormularioProveedor.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuProveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Formulario.ForPresupuesto objetoForPresupuesto = new Formulario.ForPresupuesto();
        DpFormulario.add(objetoForPresupuesto);
        objetoForPresupuesto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        Formulario.ForPresupuesto objetoFormularioPresupuesto = new Formulario.ForPresupuesto();
        DpFormulario.add(objetoFormularioPresupuesto);
        objetoFormularioPresupuesto.setVisible(true);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Formulario.ForBuscarProveedor objetoProveedor = new Formulario.ForBuscarProveedor();
        DpFormulario.add(objetoProveedor);
        objetoProveedor.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void BackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackupMouseClicked
        Respaldo instanciaRespaldo = new respaldo.Respaldo();
       
        try {
            instanciaRespaldo.crearBackup();
            JOptionPane.showMessageDialog(null, "Respaldo creado con exito");
        } catch (IOException error) {
            System.out.println(error);
        }

    }//GEN-LAST:event_BackupMouseClicked

    private void jMenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MouseClicked
        Restauracion instanciaRestauracion = new restauracion.Restauracion();

        try {
            instanciaRestauracion.crearRestauracion();
            JOptionPane.showMessageDialog(null, "Restauracion creada con exito . ");
        } catch (IOException error) {
            System.out.println(error);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7MouseClicked

    private void BackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupActionPerformed
Respaldo instanciaRespaldo = new respaldo.Respaldo();
       
        try {
            instanciaRespaldo.crearBackup();
            JOptionPane.showMessageDialog(null, "Respaldo creado con exito");
        } catch (IOException error) {
            System.out.println(error);
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_BackupActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
     Restauracion instanciaRestauracion = new restauracion.Restauracion();

        try {
            instanciaRestauracion.crearRestauracion();
            JOptionPane.showMessageDialog(null, "Restauracion creada con exito . ");
        } catch (IOException error) {
            System.out.println(error);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Respaldo instanciaRespaldo = Respaldo.getInstance();
        Restauracion instanciaRestauracion = Restauracion.getInstance();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Backup;
    private javax.swing.JLabel DpFormulario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuProducto;
    private javax.swing.JMenuItem jMenuProveedor;
    private javax.swing.JMenu jMenuVender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
